FROM node:16.17.0-bullseye-slim AS build-stage

WORKDIR /usr/src/app

COPY . .

RUN npm ci

RUN npm run build


FROM node:16.17.0-bullseye-slim

WORKDIR /usr/src/app

COPY --from=build-stage /usr/src/app/dist dist

RUN npm install -g serve

CMD ["serve", "-s", "dist"]