FROM denoland/deno:alpine-1.36.4

EXPOSE 4000

WORKDIR /usr/src/app

COPY deps.js .

RUN deno cache deps.js

COPY . .

RUN rm ./prod.env

CMD [ "run", "--unstable", "--watch", "--allow-net", "--allow-read", "--allow-env", "app.js" ]