FROM denoland/deno:alpine-1.36.4

EXPOSE 4000

ENV MODE="production"

WORKDIR /usr/src/app

COPY deps.js .

RUN deno cache deps.js

COPY . .

CMD [ "run", "--unstable", "--allow-net", "--allow-read", "--allow-env", "app.js" ]