name: cd

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  ELEPHANTSQL_URL: ${{ secrets.ELEPHANTSQL_URL }}
  VITE_GITHUB_CLIENT_ID: ${{ secrets.VITE_GITHUB_CLIENT_ID }}

jobs:
  deploy:
    name: Deploy app to fly.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Set build args and deploy
        run: |
          flyctl deploy \
            --build-arg CLIENT_ID=${{ secrets.CLIENT_ID }} \
            --build-arg CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} \
            --build-arg ELEPHANTSQL_URL=${{ secrets.ELEPHANTSQL_URL }} \
            --build-arg VITE_GITHUB_CLIENT_ID=${{ secrets.VITE_GITHUB_CLIENT_ID }} \
            --remote-only